### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by pangya** [hsreina/pang.dll-sample#1]
Reina, I believe that no one could implement this dll to operate in conjunction with your game-server.
I would love to implement this DLL in my language 'Csharp' but we need information on how to do this, is there any particular type of encryption? Could you please give us more information? Taking advantage, congratulations on your project.

**Comment by hsreina** [comment]
Well, you'll can't implement it in c# because I don't think we can use c# class libraries from c++.
About the particular encryption, it's just Pangya encryption nothing more, nothing less.
